### ISSUE TITLE
Audio details

### ISSUE THREAD

**Issue by guiandrade2** [serenadeai/speech-recorder#14]
I have looked through the code trying to find the default parameters for the sounds recording (sampling rate, bit depth, channels, encoding) but the values I found as default there ( sampling rate = 44100 Khz, bit depth = 8 , channels = 2, encoding = ?) don't seem to add up when I run the raw audio through conversion processes. Is there a reliable way of checking these details?

**Comment by tmacwill** [comment]
apologies for the hugely delayed response here, but this library uses 16-bit, single-channel audio. the sample rate is 16000 unless otherwise specified in the constructor.
