### ISSUE TITLE
pkg build

### ISSUE THREAD

**Issue by SinLT** [serenadeai/speech-recorder#27]
![image](https://user-images.githubusercontent.com/20736404/183534650-558a5da9-cdcb-42cf-8718-19046f03098d.png)

The program automatically exited when the recording started. How to package the EXE，Thank you

**Comment by tmacwill** [comment]
apologies for the hugely delayed response! it's hard to debug from that screenshot alone, but https://github.com/serenadeai/serenade/tree/master/client is an example cross-platform electron application that uses this library.
