### ISSUE TITLE
ASIO build & electron

### ISSUE THREAD

**Issue by tillderoquefeuil** [serenadeai/speech-recorder#28]
Hi there and thank you for your awsome work!

Recently I needed to work with multi-channel and an asio device.
I forked the repo and add those features.

Working in a small node project everything is going pretty fine.
(except some crashes on stream opening [like one on ten times] and returns a 3221225477 exit code)

But when I use it in an electron project it I can't even open a stream. It instant crash every time with a 3221226505.

I'm aware it's not a real issue here, I'm stuck and I hope it rings a bell to someone here.

[the forked repo](https://github.com/micorp-studio/speech-recorder)

Thanks in advance

**Comment by tillderoquefeuil** [comment]
Hi @dsouza95 ! Unfortunately I didn't find a way to do it with SpeechRecorder.

I did my own package using Audify module (it embeds an RtAudio binding that already work with [most of] Asio devices) and recreate a basic SpeechRecorder logic with WebRtcVad and SileroVad. I did it in js so it's not as good as the original but it works.

I can push a repo with it if you want me to, let me know!

**Comment by dsouza95** [comment]
Thanks for the reply @tillderoquefeuil! I actually have just found a way to fix the problem (at least, for my case), by fixing the asar paths (see #31). But it is good to know there are alternatives :)

**Comment by tmacwill** [comment]
apologies for the hugely delayed response here! I believe @dsouza95 is correct above, so will close out this issue as a duplicate.
