### ISSUE TITLE
duplex recording device (laptop audio) not recording from input

### ISSUE THREAD

**Issue by korodarn** [serenadeai/speech-recorder#29]
In pavucontrol I have set my input audio device to use the microphone and this works with discord, but with this library I am getting the output audio recording instead of input. 

I couldn't find documentation/example anywhere for how to change the input source.  Is this possible to do, and if so, how?

Thanks!

**Comment by tmacwill** [comment]
apologies for the delayed response! thanks for the report, fixed in https://github.com/serenadeai/speech-recorder/commit/5c80bb69ce6af7e59b1158223b2b27714496013e.

**Comment by korodarn** [comment]
Thanks!
